language: python
python:
  - "3.6"
# command to install dependencies
install:
  - make init
  - make install
# command to run tests
script:
  - make test # or py.test for Python versions 3.5 and below