language: python
python:
  - "3.6"
  - "2.7"
# command to install dependencies
install:
  - make init
  - make install
# command to run tests
script:
  - make test # or py.test for Python versions 3.5 and below

before_script: # configure a headless display to test plot generation
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

notifications:
  email:
    recipients:
      - mbhall88@gmail.com
    on_success: never # default: change
    on_failure: always # default: always